### ISSUE TITLE
The failAfterError option does not work

### ISSUE THREAD

**Issue by kksandr7** [adorade/gulp-stylelint-esm#27]
Hi, the failAfterError option doesn't work because the error is thrown via `this.emit('error', new PluginError(...))` instead of being passed to `done(new PluginError(...))`.

I suggest replacing all `this.emit('error', new PluginError(...))` calls with `done(new PluginError(...))`.
It's also worth adding test coverage so this error doesn't happen again.

**Comment by adorade** [comment]
Thanks @kksandr7 for reporting this issue. I will check later.

**Comment by adorade** [comment]
@kksandr7 
I attempted to replicate your issue without altering the code in any way. The process terminated upon encountering the error. The `failAfterError` option defaults to `true`, so it's not essential to specify it in the configuration. Perhaps the issue lies with your test or the configuration of your plugin or gulp task. Can you provide more information about your configuration?

Meantime I've created the missing tests for `failAfterError`. See #29

**Comment by adorade** [comment]
I need more information about your gulp configuration.

**Comment by adorade** [comment]
Thank you! I'll investigate more closely next week.

**Comment by adorade** [comment]
I understand your issue. Normally, the process should halt and not create a `dist` directory and copy the `*.css` files. The main purpose of this module is to detect errors in the source code and perform linting, rather than to copy or transfer files. The correct configuration is as follows:

```js
import { src, series } from 'gulp';
import gStylelintEsm from 'gulp-stylelint-esm';

function stylelint() {
  return src('fixtures/*.css')
    .pipe(gStylelintEsm({
      failAfterError: true, // can be omitted, true is default
      config: { rules: { 'color-hex-length': 'short' } },
      reporters: [{ formatter: 'string', console: true }],
    }));
};

function copy() {
  return src('fixtures/*.css')
    .pipe(dest('dist'));
}

const styles = series(stylelint, copy);

export default styles;
```

See more details about output here: https://github.com/kksandr7/gulp-stylelint-esm-bug/issues/1

**Comment by adorade** [comment]
The solution provided by you is not functional; it has no effect and does not resolve the issue. I am preparing a new and improved version and will close this issue.

**Comment by adorade** [comment]
Indeed, setting `failAfterError = true` should halt the stream, but it doesn't. This could be due to placing `failAfterError` within `Transform.flush` (refer to the onStreamEnd function) rather than in `Transform.transform` (refer to the onFile function). In the process of updating the **original gulp-stylelint** plugin for **stylelint v16**, it's possible that I overlooked a few aspects.

The `failAfterError` option halts the flow once the task has completed, rather than during its execution. In the next major update, I plan to address this by introducing a `failOnError` option.

The modification implemented by you failed to resolve the issue; instead, it introduced additional problems, such as the **Did you forget to signal async completion?** error. Kindly review the test results I have shared. Ensure you use the correct plugin configuration and avoid improvisation. If you enjoy and utilize this plugin, please consider starring it! ⭐ ⭐ ⭐
